In [2]:
#Question-1
#Numpy
import numpy


def arrays(arr):
    array = numpy.array(arr , float)
    return array[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

5
[5.]


In [5]:
import numpy
a = int(input())
list1 = []
for i in range(a):
    b = int(input())
    list1.append(b)
    
#print(list1)
array = numpy.array(list1)
print (numpy.reshape(array,(3,3)))



9
1
2
3
4
5
6
7
8
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Question-2
#Concatenate
import numpy
N,M, P= map(int, input().split())
A= numpy.array([ ( input().split())  for i in range(N)] , int  )
B= numpy.array([( input().split())  for i in range(M)] ,int )

print (numpy.concatenate((A,B),axis =0))

In [8]:
#Array Mathematics
import numpy
N, M = map(int, input().split())

A = numpy.array([list(map(int, input().split())) for i in range(N)])
B = numpy.array([list(map(int, input().split())) for i in range(N)])

print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)
print(A ** B)

2 2
2 2
2 2 
2 2 
2 2
[[4 4]
 [4 4]]
[[0 0]
 [0 0]]
[[4 4]
 [4 4]]
[[1 1]
 [1 1]]
[[0 0]
 [0 0]]
[[4 4]
 [4 4]]


In [ ]:
#Sum And Product
import numpy
N, M = map(int, input().split())
A= numpy.array([ ( input().split())  for i in range(N)] , int  )
B = numpy.sum(A, axis = 0) 
print( numpy.prod(B, axis = 0) )          

In [2]:
#Linear Algebra

import numpy
a = int(input())
A = numpy.array([input().split() for _ in range(a)], float)


Y =  round(numpy.linalg.det(A),2)
print(Y)


2
1 2 
3 4
-2.0


In [10]:
#inner and outer
import numpy
#m = int(input())
#A = numpy.array(int ,input().split() for i in range(m) )
#B = numpy.array(int ,input().split() for i in range(m))
A = numpy.array(input().split()  , int )

B = numpy.array(input().split()  , int )
print (numpy.inner(A, B))
print (numpy.outer(A, B))

0 1
3 4
4
[[0 0]
 [3 4]]


In [13]:
# zeroes and ones
import numpy

N = tuple(map(int, input().split()))
print(numpy.zeros(N, int))
print(numpy.ones(N, int))

3 4 5
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [ ]:
#Eye and identity
import numpy
n, m = [int(x) for x in input().strip().split()]
numpy.set_printoptions(legacy = '1.13')

print(numpy.eye(n, m))


In [ ]:
# Shape and reshape
import numpy
#a = int(input())
array = [int(x) for x in input().strip().split()]
numpy.set_printoptions(legacy = '1.13')

print(numpy.reshape(array ,(3,3)))


In [ ]:
#min and max
import numpy
N , M = map(int ,input().split())

array = numpy.array([input().split() for _ in range(N)],int)
a = numpy.min(array, axis=1)
print(numpy.max(a, axis=0))

In [ ]:
#floor ceil and rint
import numpy
array = numpy.array(input().split() , float)
numpy.set_printoptions(legacy = '1.13')
print (numpy.floor(array))
print (numpy.ceil(array))
print (numpy.rint(array))

In [ ]:
#transpose and flatten
import numpy
N , M =  map(int , input().split())
array = numpy.array([input().strip().split() for _ in range(N)], int)
print (numpy.transpose(array))
print (array.flatten())


In [ ]:
#mean variance and std
import numpy
N , M =  map(int , input().split())
array = numpy.array([input().strip().split() for _ in range(N)], int)
print (numpy.mean(array, axis = 1))
print( numpy.var(array, axis = 0) )        
d = (numpy.std(array , axis = None))
f = round(d,11)
print(f)          

In [1]:
#Dot and cross
import numpy
N = int(input())
array1 = numpy.array([input().split() for _ in range(N)], int)
array2 = numpy.array([input().split() for _ in range(N)] , int)
print(numpy.dot(array1 , array2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [ ]:
#Polynomial
import numpy
array = numpy.array(input().split(),float)
x = int(input())
print(numpy.polyval(array,x))